version: '3.4'

services:
  eventstore.db:
    image: eventstore/eventstore:latest
    mem_limit: 512m
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: cookbook_eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: cookbook_eventstore-volume-logs
        target: /var/log/eventstore
  ravendb.db:
    image: ravendb/ravendb:latest
    mem_limit: 512m
    ports:
      - "8080:8080"
      - "38888:38888"
    environment: 
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=true
      - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
    volumes:
      - cookbook_ravendb-volume-data:/opt/RavenDB/Server/RavenData
      - cookbook_ravendb-volume-config:/opt/RavenDB/config
  cookbook.backend:
    image: markplunkett/cookbook-backend:latest
    mem_limit: 512m
    ports:
      - "5000:80"
    depends_on: 
      - "eventstore.db"
      - "ravendb.db"
    environment: 
      WAIT_HOSTS: eventstore.db:1113, ravendb.db:8080
  cookbook.frontend.react:
    image: markplunkett/cookbook-frontend-react:latest
    mem_limit: 512m
    ports:
      - "3000:3000"
    depends_on: 
      - "cookbook.backend"

volumes:
  cookbook_eventstore-volume-data:
  cookbook_eventstore-volume-logs:
  cookbook_ravendb-volume-data:
  cookbook_ravendb-volume-config:
